### ISSUE TITLE
Issues #3

### ISSUE THREAD

**Issue by OhBall** [jeffdeliso/discors#3]
Great job so far! Some of the things that I'm going to list aren't issues per say, but suggestions that I'll leave up to you if you want to change/implement.

- [x] We don't want any dead links in our apps. The `Download for macOS` button should either be changed to something else or removed.

- [x] If the settings cog in the bottom left isn't going to have a separate menu pop-up, you may want it to be more obviously a logout button.

- [x] There should be an ability to leave servers that you are not an admin of.

- [x] In your MVP's you list that only an admin of a channel should be able to create text channels. However, i t may be good to keep the functionality it as is for demoing purposes. Feel free to amend your MVP's if you decide against it.

- [x] There is currently no ability to delete text channels (as far as I can tell). If anyone can create a text channel, at the very least the admin should be able to delete them.

- [x] Currently no ability to accept friend requests.

**Comment by jeffdeliso** [comment]
These features are already included

**Comment by jeffdeliso** [comment]
Address all the issues.
