### ISSUE TITLE
how do i install this discors? no instructions.

### ISSUE THREAD

**Issue by ghost** [jeffdeliso/discors#6]

**Comment by ghost** [comment]
please help me!

**Comment by xero-lib** [comment]
I mean do you know how to use Ruby?

**Comment by xero-lib** [comment]
It just takes a little debugging. As long as you know what you're doing, you'll be fine! I know absolutely no ruby but managed to get it up and running!

**Comment by ghost** [comment]
> It just takes a little debugging. As long as you know what you're doing, you'll be fine! I know absolutely no ruby but managed to get it up and running!

i've never used ruby in my life
can you please help me
